### ISSUE TITLE
Define and implement an actions API

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-runner#124]
Currently we have an ad-hoc mixture of docker images, some of which take arguments, some of which don't.

Pick a single API for the entrypoints, and implement it in our project-parsing/docker-invocation in `job-runner`, and across [all the current docker images](https://github.com/opensafely/job-runner/blob/548938db700572ac84a2bf1da53f0a7bcee0f462/jobrunner/config.py#L43).

My straw man is that any `run` command can call only one executable as its entrypoint (e.g. `python`, `jupyter`, `Rscript`), and can accept a single argument, which is a JSON-formatted set of arguments.

This gives a portable way to pass structured arguments from YAML to different lanagues. Something like:

```yaml

actions:
  run_model:
    run: stata-mp
    positional_args:
        - model.do
    keyword_args:
       colour: 
          green
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        model: models/cox-model.txt
```

We could also consider requiring that a run action is a repo containing a Dockerfile and documentation in a specific format; this could then be included in our actions library automatically.

Of course, there's no need to reinvent the wheel so we'd be as well to consider what Github Actions does here.

**Comment by bloodearnest** [comment]
I've have been discussing a similar image entrypoint API with @evansd. Right now, we have python and jupyter images, which are virtually identical. We've got other actions we want to implement (e.g. matching). 

I think we should have a standard entrypoint for each image that supports invoking multiple tools, as indicated by the action.

e.g

`run: python` would use the python image, and the entrypoint would invoke the base python executable
`run: jupyter` would use the same image, and the entrypoint script would invoke jupyter
`run: safetab` would use the python image, entrypoint script would invoke safetab
`run: matching` would use the python image, entrypoint script would invoke osmatching.
`run: r` would use the R image, and invoke Rscript
`run: r-jupyter` would use the R image, and invoke R's jupyter kernel,


So the mapping in job-runner from action to invocation would look something like:

    python: {image: python, cmd: python},
    jupyter: {image: python, cmd: jupyter},
    safetab: {image: python: cmd: safetab}
    matching: {image: python: cmd: matching}

Docker image wise, to use python image as an example, we have entrypoing.py, and we set the default CMD to `python`. And entrypoint.py only supports CMD values of {python,jupyter,matching,safetab}, etc, and knows how to invoke each one.

**Comment by evansd** [comment]
Hey @bloodearnest , don't have time to comment in detail but I seem to remember this isn't what we ended up agreeing on because it breaks the simple mapping from "run" arguments to docker invocations. Instead we had a scheme for putting more logic in the entry point script so it would look more like "run: python:latest jupyter"

**Comment by bloodearnest** [comment]
> Hey @bloodearnest , don't have time to comment in detail but I seem to remember this isn't what we ended up agreeing on because it breaks the simple mapping from "run" arguments to docker invocations. Instead we had a scheme for putting more logic in the entry point script so it would look more like "run: python:latest jupyter"

I know we discussed this, but must have misremembered which side we came down on, apologies. However, `run: {image:version} {action}` I think actually complicates things a bit.

1. We need to support pinning versions, and ideally pinning to the *action* version, not the underlying python image version. For example: "Matching 1.3 has that new feature I want - wait, which version of the python image do I need to get matching 1.3?" 

2.  I don't particularly want to expose the users to the implementation details of actions. To invoke `matching` or `safetab`, they need to know to use the `python` image. I'd rather they think at a higher level than that. Plus it gives us freedom to change implementation details later w/o affecting project.yaml syntax.

3. I think there is a lot of value and simplicity in preserving the 1:1 mapping between action and image, as you say.

So, going back to the original problem I was trying to solve: I didn't want to have multiple distinct images python images for every python based action.

So here's a suggestion to solve that and the above issues, and I think is probably more typical docker-esque solution.

1. Have a base python image that has all dependencies, which is `ghcr.io/opensafely-core/python`

2. Produce one additional image each for jupyter/matching/safetab/etc action, based `FROM ghcr.io/opensafely-core/python:latest`. Each of these images has an action-specific entrypoint.

3. Images are tagged according the the *action* version, rather than the python image version.
e.g. matching 1.3. is released, we build a new image based FROM the latest python image, and tag it as matching:1.3.

4. We probably want to keep updating actions based on the changes to the base python version, even if the action version has changed. We could version this as subrelease tag, e.g. matching:1.3.0-0 exists, we build a new version based on python image changes, and tag it 1.3.0-1 or 1.3.0-pythonA.B and we move the 1.3.0 tag to point to 1.3.0-1

This provides a home for the implemenation/documentation for the per-action yaml config options I suggested above, too.

Thoughts?

**Comment by evansd** [comment]
Ah, good point about versioning and the one-image-per-action solution sounds good, and not too heavyweight if we get our docker layering right. I think we might want to do that _and_ the custom entrypoint thing as that solves a slightly different problem.

Can discuss more tomorrow.

**Comment by bloodearnest** [comment]
Some further discussions on slack here: https://ebmdatalab.slack.com/archives/C63UXGB8E/p1615910022014800

In summary:

Images:
 - we think a base python image with smaller action images based FROM it is a good plan
 - we version and tag the action version e.g. `safetab:1.1` or `python:1.2`
 - initial actions: `python`, `jupyter`, `matching`, `safetab`
 - we add a docker LABEL to signify it's an action image, e.g. `LABEL org.opensafely.action=safetab`. Images must have this label or else job-runner will refuse to run them (in addition to being opensafely-core images). This avoids us needing to hardcode the list in job-runner/openafely-cli.

Invocation and arguments:
 - we ideally want to preserve cli args as the method of invocation (as opposed to files or serialised json), as it's much nicer to debug and develop
 -  we want users to be able to pass their own cli args, but also want to provide some yaml structured config too. One option might be yaml->cli arg a convention, perhaps.

**Comment by bloodearnest** [comment]
Based on the initial [safetab implementation](https://github.com/opensafely-core/safetab-action/pull/2/files), individual cli args is not really an option due to the complexity of the config, and we realised that we also wanted to specify the input files to be derived from `needs`, rather than specifying them twice.

So, a naive implementation proposal, given the following action definition:

```yaml
    ...
    dependant_action:
        action: ...
        outputs:
            highly_sensitive:
                foo: foo.csv
                bar: bar.csv
    
    safetab_action:
        needs: [dependant_action]
        action: safetab:latest
        config:
            simple_2_way_tabs:
                tab_type: 2-way
                variables: [sex, ageband, copd]
            death_2_way_tab:
                 tab_type: target-2-way
                 variables: [sex, ageband, copd]
                 target: death
            grouped_by_sex:
                 tab_type: groupby-2-way
                 variables: [ageband, copd, death]
                 groupby: sex
```

Job-runner takes the files that would be copied into the job from its `needs` definition, as well as the `config` section, merges them info a single dict with 'inputs' key with list of input files from `needs`, and `config` key as above. Serialises this to json in a known path e.g. `metadata/safetab_action_config.json`. It then appends this file to the invocation of safetab, so that safetab just takes a single argument, the path to the json config.

Because the file is serialised to a known persistent location, this means we should be able to re-run the docker invocation manually when debugging which is nice.

We may also need to allow `filtering` the needs list of files with list of globs/regexs in the `config` section, as it's possible you don't want to run safetab on *every* output from a previous action, just some.

**Comment by sebbacon** [comment]
This is readable which is nice. 

1. Does it need some kind of tooling for a person developing an action to develop / test / validate / prove the YAML -> JSON path?
2. I can imagine we'd want the filter option sooner rather than later. What would it look like? I wonder if it would actually be its own action, so it can apply to any set of files, rather than an option for safetab (and other yet-to-be-implemented actions)? Or just a standard option as a top-level key in each action config?

**Comment by bloodearnest** [comment]
1) It doesn't need a tool, but it perhaps needs documenting? @CarolineMorton's used an initial prototype in her implementation here: https://github.com/opensafely-core/safetab-action/pull/2/files

2) So, I was thinking to default to all files, but a top level key in the config that is a filter on the needs.

So, per above:

```yaml
    config:
        files: [foo.csv]
        simple_2_way_tabs:
            ...
```

The job runner can do the filtering, so the action json just has the final list of files?

**Comment by sebbacon** [comment]
So the "action API" is this, right?

* Your docker container must accept an argument `--config`, which is a path to a JSON file
* The JSON file will have an `inputs` key, which is an array of file paths to the outputs of `need`ed actions, optionally filtered by X (see below for more discussion on that)
* The JSON file will have a `config` key, which is a JSONified version of the `config` key for the action that invokes the docker container

We also need to assert some kind of contract about the output files. Perhaps this is just by requiring it to be clear in the documentation: some actions might always output a file called `frob.png`; the action @CarolineMorton is working on always makes tables that are predictably named based on the input.  I can't think of a better way of dealing with this other than requiring a section "output file paths" in an action documentation...

The other output type is logging. Again, I suspect this should be a required section in the documentation.

For the file-filtering, it seems to me that if the *framework* is going to handle this, it shouldn't be part of the `config` key, which should be entirely under the auspices of the action runner.

I'd also prefer something a more explicit name than `files`, e.g. `input_file_filter`.  I think it should probably also be globbed, and should be an array. So how about:

```yaml
    dependant_action:
        action: ...
        outputs:
            highly_sensitive:
                foo: foo.csv
                bar: bar.csv
    
    safetab_action:
        needs: [dependant_action]
        input_file_filter: [foo.*]
        action: safetab:latest
        config: ...
```

**Comment by evansd** [comment]
On this remark here:

> Serialises this to json in a known path e.g. `metadata/safetab_action_config.json`. It then appends this file to the invocation of safetab, so that safetab just takes a single argument, the path to the json config.
>
> Because the file is serialised to a known persistent location, this means we should be able to re-run the docker invocation manually when debugging which is nice.

This file needs to be accessible _inside_ the container, which means either copying it to the volume each time, or mounting an extra directory with the file in it.

I know I've suggested this before to a rather lukewarm reception (:smile: ) but is it worth considering passing in the JSON itself as an arg? We'd want to do it minified, rather than pretty-printed to save space. But I don't think quoting will be an issue. If we enclose in singe quotes then the only character which needs escaping is the single quote itself, which isn't going to be that common. We can either replace that with `'\''` or, better I think, with `\x27`. The latter works because single quote can only occur inside a string literal in JSON where hex escape sequences are valid. This means that the entire string stays as copy-pastable valid JSON without needing to undo any bash escaping.

`MAX_ARG_STRLEN` is 131,072 which I think we're unlikely to bump into.

**Comment by sebbacon** [comment]
One issue with the serialised-JSON-as-argument route is the action-author-dev-and-debugging story. Especially if we're going to ask them to escape it with special rules when testing, and unescape it in their code?

Or were you thinking this is an implementation detail within the job runner, and the action can still assume a configuration file at a certain path?

**Comment by evansd** [comment]
I think the local development story is just:
```
docker run ... blah blah .. --config "$(cat test-file.json)"
```

There's no escaping required there at all.

And the point of using the `\x27` hex sequence is that there's no specific unescaping required by the consumer anyway: it's part of the JSON standard and `json.loads` or its equivalent will handle that for you.

**Comment by bloodearnest** [comment]
Regards being accessible inside the docker, I was thinking it would be generated as a permanent output in the medium security outputs in the workspace, and as you say, copied into the volume with the rest of the input files. It could then be shipped to level 4. 

That provides 2 benefits to my mind:

1) You can see exactly what actual config an action ran with with when debugging why an action didn't work from level 4, especially useful if your input files are globs, so only realised at run time.

2) Still preserves docker transparency, its the same debugging command: e.g.

    docker run -v $volume:/workspace safetab --config action_foo_config.json

**Comment by evansd** [comment]
Ah, I had missed the bit about the config including the list of output files from dependencies. I can see why this might be desirable, but I think we should consider seriously whether we want to do it. It's quite a big extra piece to add to the currently quite simple contract between job-runner and the actions it runs.

If this can be done via some mixture of conventions and passing directories or glob patterns to the output then it might be worth the slight loss of ergonomics for the long term conceptual simplicity.

In any case, this feels like a larger discussion than can sensibly be had in a issue thread. Should me, @bloodearnest and @CarolineMorton try to have a chat about this next week?

**Comment by bloodearnest** [comment]
Just to update this, @evansd, @CarolineMorton  and I did get together and discuss this some more.

The conclusion was 

1. Actions should support both `--config path/to/json` and `--config 'serialised json string'`. Jobrunner will implement the latter initially and see how it goes.
2. Action input should be explicitly listed in the `run:` line, according to action. So some actions may just list one or two input files as positional arguments, and others might require options, e.g. `--input file1.csv --control file2.csv`
3. We may add an environment variable that lists all input files to the action, in case that is useful for some actions.

So an action definition that looks like this:
```
actions:
    myaction:
         run: action:latest file1.csv file2.csv
         config:
              foo: bar
```

Would be serialised as:

`docker run ... ghcr.io/opensafely-core/action:latest file1.csv file2.csv --config '{"foo": "bar"}'`

or maybe this down the line:

`docker run ... ghcr.io/opensafely-core/action:latest file1.csv file2.csv --config path/to/json`

**Comment by CarolineMorton** [comment]
matching, safetab-action and cohort-report action all have the same structure and are invoked in a similar way:

**repo structure:**
```tree
|-- action_folder 
|   |-- __init__.py
|   |-- __main__.py
|   |-- action_file.py
|   |-- action_processing.py
|   |-- version.py
|-- docs
|   |-- README.md  # this is meant to directly pulled into documentation
|-- tests
|   |-- test_action_file.py
|   |-- test_action_processing.py
|-- Makefile # all the commands for running tests including test_docker build
|-- dev_requirements.txt
|-- Dockerfile
|-- setup.py
```

The action can be locally installed via `pip install .` for testing and development. The docker image can be via the commands in Makefile and tested locally. The Dockerfile builds on the existing python image and has a entrypoint defined. See example below. 

**Dockerfile**
```docker
# Grab the docker python image
FROM ghcr.io/opensafely-core/python:latest as base-python

# local install
COPY ./ ./
RUN python -m pip install .

# labeling
LABEL org.opencontainers.image.title="safetab" \
      org.opencontainers.image.description="Safetab action for opensafely.org" \
      org.opencontainers.image.source="https://github.com/opensafely-core/safetab-action" \
      org.opensafely.action="safetab"

# re-use entrypoint from base-docker image
ENV ACTION_EXEC=safetab```

**Comment by CarolineMorton** [comment]
The `__main__.py` file has a similar structure across all 3 actions. 

There is an `ActionConfig` class that validates the --config passed in. See [safetab](https://github.com/opensafely-core/safetab-action/blob/39adc746cd2bf802bf89a5b5e6ab5c6da69d2edf/safetab/__main__.py#L11). 

There is a function that loads the config, and replaces default values where the [config](https://github.com/opensafely-core/safetab-action/blob/39adc746cd2bf802bf89a5b5e6ab5c6da69d2edf/safetab/__main__.py#L68) demands this.

Then there is a `main` function that is the command line tool. It takes in a config with a `--config`  flag and validates with the `ActionConfig`. The other commands can be added here. safetab for example just takes in a list of files as the first argument, whereas matching looks for `--cases` and `--controls`.

@bloodearnest have i missed anything here?

**Comment by CarolineMorton** [comment]
This is an example of how it would be invoked:
```
actions: 
  match_cohorts:
    run: match:latest --cases input_case.csv --controls input_controls.csv
config:
  matches_per_case: 3
  match_variables:
    sex: category
    age: 5
  index_variable: indexdate
  closest_match_columns:
      - age
  input_path: tests/test_data
  output_path: tests/test_output/test_1
```

What we don't have yet is job runner working with this. There is a missing step where the config gets changed into JSON and passed in as a `--config` argument. See discussions above about how this would be best implemented.

**Comment by iaindillingham** [comment]
I think that we can close this issue, because it has been subsumed by:

* opensafely-core/job-runner#225
* opensafely-core/job-runner#227
* opensafely-core/job-runner#228
* opensafely-core/actions-registry#7
* A recent discussion about versioning images (runtimes) and actions
