### ISSUE TITLE
Send non-disclosive, transient errors back to job server

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-runner#184]
There are certain errors thrown inside jobs which are non-disclosive which are currently hidden and should be dispalyed to Users on the website.

I think we still want to be very careful with what we expose so maybe some sort of allow list for these?

**Comment by ghickman** [comment]
This issue was prompted by [two](http://jobs.opensafely.org/jobs/ahccqrmes77fuoqz/) [jobs](http://jobs.opensafely.org/jobs/tvqompymgjl66hsc/) failing with opaque errors.

On the server we can see something is up with the connection to the database becuse the logs end with `_tds.DatabsaeError: DBPROCESS is dead or not enabled`.

**Comment by sebbacon** [comment]
When notebooks run out of memory: `nbconvert.preprocessors.execute.DeadKernelError: Kernel died`

**Comment by sebbacon** [comment]
In EMIS, when intermittent presto errors occur: `type=INTERNAL_ERROR, name=TOO_MANY_REQUESTS_FAILED`

**Comment by evansd** [comment]
It's worth saying that in a sense this errors aren't "hidden" in that we don't do anything active to suppress them: they just occur inside the container and so at a level to which job-runner doesn't have direct access. So exposing these to the user would involve something like grepping the log files to look for certain lines and then mapping these to error messages.

I guess a crude implementation would be to maintain a lookup table of regexes to error messages which we'd run over the log file (or the last N lines of it).

**Comment by sebbacon** [comment]
For the record, here's another transient SQL Server error seen in the wild

`_tds.DatabaseError: Unexpected EOF from the server`

**Comment by evansd** [comment]
Just been bitten again by the above error here: https://jobs.opensafely.org/jobs/u2hdxjbgnxespxhk/

**Comment by evansd** [comment]
The job-runner is currently undergoing fairly major surgery to prepare for running against multiple execution environments, rather than just local Docker as it does currently (see e.g. #273 #280). This means now is not really the time to be introducing this kind of change. Instead we should think about how best to support this kind of feature via the new APIs being developed.

**Comment by sebbacon** [comment]
The last comment here is "don't do it yet". We are now post-surgery, and I've recently been having to debug database disconnections and similar, which still report simply as `error 1`.

Are we in a position to spec out some minimal improvements to allow end users to disambiguate memory and database connection errors?

**Comment by evansd** [comment]
We now already have code which special cases exit code 137 and lets the user know that this probably means a memory issue:
https://github.com/opensafely-core/job-runner/blob/663b736960da4a5f80bc53b4b68ef805b15a5803/jobrunner/executors/local.py#L242-L245

I think the most practical short term improvement here would be to update cohortextractor so that it catches certain sorts of database error and then exits with specific error codes. This isn't an ideal communication channel but it's one we can use without any additional design work.

Additionally identifying these errors is probably going to involve string matching on the exception message, which adds another layer of yuckiness, but again I don't see an alternative.

I guess at a minimum the two conditions we need to catch are `EOF from server` and `CodedEvent_SNOMED table does not exist`.

As to what exit codes we use, here are some pre-existing ones to avoid:
https://tldp.org/LDP/abs/html/exitcodes.html
https://www.freebsd.org/cgi/man.cgi?query=sysexits&apropos=0&sektion=0&manpath=FreeBSD+4.3-RELEASE&format=html

**Comment by evansd** [comment]
Once this associated issue is closed:
 * https://github.com/opensafely-core/cohort-extractor/issues/776

We'll need to extend the list of specially handled exit codes here:
https://github.com/opensafely-core/job-runner/blob/663b736960da4a5f80bc53b4b68ef805b15a5803/jobrunner/executors/local.py#L242-L245

The associated messages we want to convey are (roughly speaking):
 * `EOF from server` -> "A transient database error occurred, your job may run if you try it again, if it keeps failing then contact tech support"
 * `CodedEvent_SNOMED` missing -> "New data is being imported into the database, please try again in a few hours"
 * `Generic database error` -> "Something went wrong with the database, please contact tech support"
