### ISSUE TITLE
Fix manifest.json for reusable actions

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-runner#236]
Reusable actions (opensafely-core/job-runner#234) are run by, in effect, rewriting *project.yaml*. However, this isn't reflected in *manifest.json*: the repo and commit point to the study's repo and commit and not to the reusable action's repo and commit.

**Comment by evansd** [comment]
### Problem

> the repo and commit point to the study's repo and commit and not to the reusable action's repo and commit.

Actually the problem is almost the opposite of this, although not quite! To clarify...

Each Job in the database has a `repo_url` and a `commit`. For "traditional" actions these refer to the project repo. For reusable actions they refer to the action repo. (This is nice because most of the code doesn't have to know what a reusable action is: it just needs to build a container from a given commit and run it.)

At the moment `manfiest.json` looks like this:

```json
{
  "files": {
    "output/input.csv": {
      "created_by_action": "generate_cohort",
      "privacy_level": "highly_sensitive"
    }
  },
  "actions": {
    "generate_cohort": {
      "state": "succeeded",
      "commit": "94a2b57de486cff7dc4f4ad932ef92648f370cdc",
      "docker_image_id": "sha256:5bdb61612a16ecb4a4d7278351a9faad1484e917d0b49eddc27cb253cce8a44b",
      "job_id": "3spadsawfame3xdb",
      "run_by_user": "evansd",
      "created_at": "2021-01-11T17:52:08Z",
      "completed_at": "2021-01-11T17:52:25Z"
    }
  },
  "workspace": "households-research",
  "repo": "https://github.com/opensafely/households-research"
}
```

Note that each action has a `commit` field but there's a single top-level `repo` field. It gets set each time we update the manifest by taking the `repo_url` of the job that just ran. This made sense in the old world as all commits would come from the same repo. However in the new world, if the last action you ran was a reusable action then `repo` in the manifest will point to the repo of the reusable action, which is bad.

---

### Solution

I've realised that for reproducibility we need to actually need to record in the manifest _both_ the original commit in the project repo which invoked the reusable action, and the commit in the reusable actions repo which eventually got run. This is because the action configuration (by which I mean the list of input files it consumes and outputs it generates as well as any command line flags) isn't captured in the action commit.

I think this means adding fields to the Job model like `workspace_repo_url` and `workspace_commit` (or should it be "project"? "workspace" seems less overloaded to me) which always record the original, pre-reusable-actions values. We use these to set `commit` and `repo` in the manifest. Then, additionally, in the case that `job.commit != job.workspace_commit` we record those values as `action_commit` and `action_repo`. Conceptually these belong alongside `docker_image_id`; they are a record are the specific version of externally supplied code that was used to run the action.

It's slightly unpleasant that the reusable actions stuff ends up bleeding out into the manifest structure like this but I don't see any alternative, and I'm hopeful that this is close to the last of the wider changes it introduces.

---

### Wrinkle

Unavoidably, this will involve changing the database schema which means doing a database migration which we currently have no machinery for doing.

If you can find a time when there are no jobs running then this is actually very easy. Just stop the job-runner, delete its database and restart! (The database is designed to be ephemeral, everything we're interested in long term is written to disk.)

If you can't find such a time then it's not too difficult but is annoyingly manual:
 * Stop the job-runner (it's fine to do this while there are jobs running).
 * Make a backup copy of the database just in case.
 * Run `ALTER TABLE` to add the columns and populate using the existing `commit` and `repo_url` columns.
 * Restart the database.

I think this will be only the second db migration we've ever needed to do, and we only had one deployment at the time, but as time goes on we're obviously going to need to come up with a better way of handling these.

**Comment by iaindillingham** [comment]
Ouch, looks harder than I realised! Thanks for clarifying @evansd.
