### ISSUE TITLE
Add a reusable action to the integration test

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-runner#237]
It would be good to add a reusable action (#234) to the integration test.

**Comment by iaindillingham** [comment]
We think this is easier than it looks! We already call a remote repo when testing job-runner; we could call another ([`opensafely-actions/minimal-action`](https://github.com/opensafely-actions/minimal-action)) when adding a reusable action to the integration test. I *think* (🤞🏻) this might be as simple as adding another action to the study within the integration test.

**Comment by evansd** [comment]
I think that's fine in the first instance. Further down the line I'd like to move towards making the integration test fully local again but I don't see a problem with adding an external dependency in the short term.

The current set of remote repo tests are for testing specific operations on Github for which there's no other reliable testing mechanism than calling the real thing. So in that sense they're an exception rather than a model to copy.

**Comment by iaindillingham** [comment]
Closed by opensafely-core/job-runner#256.
