### ISSUE TITLE
release process: allow users option to delete files

### ISSUE THREAD

**Issue by annaschultze** [opensafely-core/job-runner#269]
I think I've asked before, but it'd be really convenient to be able to delete files on L4. For example, I accidentally created a copy of a folder, and now cannot remove it. I would also like to remove 3 outputs that are no longer used from a folder, so that I can commit the entire folder for release without having these 3 files checked for release. I know I can commit individual files, but there are 30+ files in the folder and it saves a lot of typing to select the entire folder... 

Also not sure if this is the right place to post - happy to open an issue somewhere else.

**Comment by wjchulme** [comment]
related:  #173

**Comment by wjchulme** [comment]
In fact, #173 is basically the same issue. So I'm going to close.

You can delete files from L4 but since they are not deleted from L2/3, where they are copied across from, they re-appear a few minutes later. 

The only files that remain deleted are those that have also been deleted from L2/3. This can happen in one of two ways:

* Delete the file(s) "manually". This is not possible for most users due to permissions.
* In an action's outputs, specify a glob that captures the file you want to delete, but that also captures a file that you want to keep. For example, if the file you want to delete is `output/figures/foo.png` but a new file that you want to keep is `output/figures/bar.png`, then specifying `output/figures/*` as an output in an action will delete `foo.png` if it's not created by the action. This is _haaacky_, and may not always be possible!

**Comment by annaschultze** [comment]
Thanks Will - I'd forgotten I'd commented on that issue as well. I might try that hacky solution, and will answer my own question on the discussions forums as well so that other users can see this. It's not hugely urgent.
