### ISSUE TITLE
Prevent large CSV files from being copied to level 4

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/job-runner#726]
We've been asked to ensure that CSV files with more than 5000 rows cannot be copied into level 4.  See discussion in [this thread](https://bennettoxford.slack.com/archives/C069YDR4NCA/p1714056557505449).

To do this, we should update `check_l4_file`:

 https://github.com/opensafely-core/job-runner/blob/ba22eb52538d18000516cd373e40196a0345f189/jobrunner/executors/local.py#L626-L668

If a user exceeds the limit, the error message should tell the user to contact tech-support.  We should then add a record to the tech-support routing table that in the first instance says "paste the issue in #team-ops and connect the researcher with Alex".

**Comment by bloodearnest** [comment]
Note: we have an existing mechanism for telling users why specifically their file has been rejected, with links to docs for that specific issue.

Those docs I think ask them to follow up with their co-pilot, I think.

I don't think we should do anything different here, just add new section to the docs.

**Comment by inglesp** [comment]
What's the existing mechanism?

**Comment by bloodearnest** [comment]
It's in the code linked, but there's a message that's set that they see on job-server, and there's a file that gets written in place of the L4 file with more information.

File contents: https://github.com/opensafely-core/job-runner/blob/ba22eb52538d18000516cd373e40196a0345f189/jobrunner/executors/local.py#L585

Note: that this mechanism was designed to work in the filesync setting. Once that has been disabled, we can probably do something better in airlock.

But I think we should just use the same mechanism we already have for this issue. It's just another check to slot into the list.

**Comment by inglesp** [comment]
And where in the docs do we tell users to follow up with their co-pilot?  All I can see is a link to https://docs.opensafely.org/releasing-files/#allowed-file-types in ..., which looks like it should actually link to https://docs.opensafely.org/requesting-file-release/#allowed-file-types.

(@rebkwok could you update the link while you're touching this file?)

**Comment by bloodearnest** [comment]
Looks like some link rot there, and it looks like the content has changed.

But I don't think we should be referring them straight to tech-support.  The file contents are fairly clear self contained documentation of why their file is not allowed, though no doubt could be improved.  This is in part because they cannot access docs.opensafely.org links from L4.

My larger point is this: we have a mechanism for this already, been in production for 6 months.  This ticket is about somewhat urgently adding an additional check.  I think it should focus on using the the current messaging framework for that.  When filesync is turned off, we can hugely improve this by having airlock handle these cases.

**Comment by rebkwok** [comment]
@inglesp Just checking - given the conversation above - that you still want a note to contact tech-support to go into the job-runner file messages.
https://github.com/opensafely-core/job-runner/pull/727#discussion_r1586251743

**Comment by rebkwok** [comment]
Never mind, I;ve read the right slack thread now
